name: CI

on: [pull_request]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo {{job.status}}

